apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-cf9cdd
spec:
  data:
    - remoteRef:
        key: cloudflare
        property: zone-api-token
      secretKey: api-token
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-api-token-cf9cdd
    template:
      engineVersion: v2
      type: Opaque
