apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oekaki-dengon-game-58e067
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: postgres
      secretKey: postgres-admin-password
    - remoteRef:
        key: postgres_passwords
        property: oekaki_dengon_game
      secretKey: postgres-user-password
    - remoteRef:
        key: seaweedfs
        property: oekaki_dengon_game_secretkey
      secretKey: minio-secret-key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oekaki-dengon-game-58e067
    template:
      engineVersion: v2
      type: Opaque
