apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-9d4624
spec:
  data:
    - remoteRef:
        key: renovate
        property: github_token
      secretKey: github-token
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-9d4624
    template:
      engineVersion: v2
      type: Opaque
