apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: renovate
  namespace: renovate
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 192.168.0.0/16
              - 10.244.0.0/16
              - 10.96.0.0/12
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  podSelector:
    matchLabels:
      app: renovate
      app.kubernetes.io/name: renovate
  policyTypes:
    - Egress
