apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mucaron-2290e1
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: mucaron
      secretKey: postgres_password
    - remoteRef:
        key: redis
        property: password
      secretKey: redis_password
    - remoteRef:
        key: mucaron
        property: session_secret
      secretKey: session_secret
    - remoteRef:
        key: mucaron
        property: minio_secret_key
      secretKey: minio_secret_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mucaron-2290e1
    template:
      engineVersion: v2
      type: Opaque
