apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-default-filer-config-f250d0
  namespace: seaweedfs
spec:
  data:
    - remoteRef:
        key: scylladb
        property: seaweedfs
      secretKey: scylladb_password
    - remoteRef:
        key: seaweedfs
        property: sts_signing_key
      secretKey: sts_signing_key
    - remoteRef:
        key: seaweedfs
        property: terraform_secretkey
      secretKey: terraform_secretkey
    - remoteRef:
        key: seaweedfs
        property: misskey_secretkey
      secretKey: misskey_secretkey
    - remoteRef:
        key: seaweedfs
        property: oekaki_dengon_game_secretkey
      secretKey: oekaki_dengon_game_secretkey
    - remoteRef:
        key: seaweedfs
        property: stalwart_secretkey
      secretKey: stalwart_secretkey
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seaweedfs-default-filer-config-f250d0
    template:
      data:
        filer.toml: |
          [leveldb2]
          enabled = false

          [cassandra2]
          enabled = true
          keyspace = "seaweedfs"
          hosts = ["scylla-cluster-client.databases.svc"]
          username = "seaweedfs"
          password = "{{ .scylladb_password }}"
          ssl_ca_path = "/etc/seaweedfs/scylladb-ca/ca.crt"
          ssl_cert_path = "/etc/seaweedfs/scylladb-client/tls.crt"
          ssl_key_path = "/etc/seaweedfs/scylladb-client/tls.key"
          localDC = "iwakura"
        iam.json: |
          {
              "sts": {
                  "tokenDuration": "1h",
                  "maxSessionLength": "12h",
                  "issuer": "seaweedfs-sts",
                  "signingKey": "{{ .sts_signing_key | b64enc }}"
              },
              "providers": [
                  {
                      "name": "k8s",
                      "type": "oidc",
                      "enabled": true,
                      "config": {
                          "issuer": "https://192.168.0.17:16443",
                          "clientId": "sts.seaweedfs.com",
                          "jwksUri": "https://kubernetes.default.svc/openid/v1/jwks",
                          "tlsCaCert": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
                          "roleMapping": {
                              "rules": [
                                  {
                                      "claim": "sub",
                                      "value": "system:serviceaccount:loki:loki",
                                      "role": "arn:aws:iam::role/loki"
                                  },
                                  {
                                      "claim": "sub",
                                      "value": "system:serviceaccount:ipu:ipu",
                                      "role": "arn:aws:iam::role/ipu"
                                  },
                                  {
                                      "claim": "sub",
                                      "value": "system:serviceaccount:misskey:misskey-postgresql",
                                      "role": "arn:aws:iam::role/cloudnative-pg-backup"
                                  },
                                  {
                                      "claim": "sub",
                                      "value": "system:serviceaccount:databases:postgresql-default",
                                      "role": "arn:aws:iam::role/cloudnative-pg-backup"
                                  },
                                  {
                                      "claim": "sub",
                                      "value": "system:serviceaccount:tempo:tempo",
                                      "role": "arn:aws:iam::role/tempo"
                                  }
                              ],
                              "defaultRole": "arn:aws:iam::role/S3DenyAllRole"
                          }
                      }
                  },
                  {
                      "name": "terraform_cloud",
                      "type": "oidc",
                      "enabled": true,
                      "config": {
                          "issuer": "https://app.terraform.io",
                          "clientId": "aws.workload.identity",
                          "jwksUri": "https://app.terraform.io/.well-known/jwks",
                          "roleMapping": {
                              "rules": [
                                  {
                                      "claim": "aud",
                                      "value": "aws.workload.identity",
                                      "role": "arn:aws:iam::role/TerraformCloud"
                                  }
                              ],
                              "defaultRole": "arn:aws:iam::role/S3DenyAllRole"
                          }
                      }
                  }
              ],
              "policies": [
                  {
                      "name": "DenyAllPolicy",
                      "document": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Deny",
                                  "Action": [
                                      "s3:*"
                                  ],
                                  "Resource": [
                                      "*"
                                  ]
                              }
                          ]
                      }
                  },
                  {
                      "name": "loki",
                      "document": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Action": [
                                      "s3:*"
                                  ],
                                  "Resource": [
                                      "arn:aws:s3:::loki-admin",
                                      "arn:aws:s3:::loki-chunks",
                                      "arn:aws:s3:::loki-ruler",
                                      "arn:aws:s3:::loki-admin/*",
                                      "arn:aws:s3:::loki-chunks/*",
                                      "arn:aws:s3:::loki-ruler/*"
                                  ]
                              }
                          ]
                      }
                  },
                  {
                      "name": "ipu",
                      "document": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Action": [
                                      "s3:Get*",
                                      "s3:List*"
                                  ],
                                  "Resource": [
                                      "arn:aws:s3:::ipu",
                                      "arn:aws:s3:::ipu/*"
                                  ]
                              }
                          ]
                      }
                  },
                  {
                      "name": "cloudnative-pg-backup",
                      "document": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Action": [
                                      "s3:*"
                                  ],
                                  "Resource": [
                                      "arn:aws:s3:::cloudnative-pg-backup",
                                      "arn:aws:s3:::cloudnative-pg-backup/*"
                                  ]
                              }
                          ]
                      }
                  },
                  {
                      "name": "tempo",
                      "document": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Action": [
                                      "s3:*"
                                  ],
                                  "Resource": [
                                      "arn:aws:s3:::tempo",
                                      "arn:aws:s3:::tempo/*"
                                  ]
                              }
                          ]
                      }
                  }
              ],
              "roles": [
                  {
                      "roleName": "S3DenyAllRole",
                      "roleArn": "arn:aws:iam::role/S3DenyAllRole",
                      "attachedPolicies": [
                          "DenyAllPolicy"
                      ],
                      "trustPolicy": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "Federated": "*"
                                  },
                                  "Action": [
                                      "sts:AssumeRoleWithWebIdentity"
                                  ]
                              }
                          ]
                      }
                  },
                  {
                      "roleName": "TerraformCloud",
                      "roleArn": "arn:aws:iam::role/TerraformCloud",
                      "attachedPolicies": [
                          "AmazonS3FullAccess"
                      ],
                      "trustPolicy": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "Federated": "*"
                                  },
                                  "Action": [
                                      "sts:AssumeRoleWithWebIdentity"
                                  ],
                                  "Condition": {
                                      "StringEquals": {
                                          "oidc:iss": "https://app.terraform.io"
                                      },
                                      "StringLike": {
                                          "oidc:sub": [
                                              "organization:walnuts-dev:project:*:workspace:*:run_phase:*"
                                          ]
                                      }
                                  }
                              }
                          ]
                      }
                  },
                  {
                      "roleName": "loki",
                      "roleArn": "arn:aws:iam::role/loki",
                      "attachedPolicies": [
                          "loki"
                      ],
                      "trustPolicy": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "Federated": "*"
                                  },
                                  "Action": [
                                      "sts:AssumeRoleWithWebIdentity"
                                  ],
                                  "Condition": {
                                      "StringEquals": {
                                          "oidc:iss": "https://192.168.0.17:16443"
                                      }
                                  }
                              }
                          ]
                      }
                  },
                  {
                      "roleName": "ipu",
                      "roleArn": "arn:aws:iam::role/ipu",
                      "attachedPolicies": [
                          "ipu"
                      ],
                      "trustPolicy": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "Federated": "*"
                                  },
                                  "Action": [
                                      "sts:AssumeRoleWithWebIdentity"
                                  ],
                                  "Condition": {
                                      "StringEquals": {
                                          "oidc:iss": "https://192.168.0.17:16443"
                                      }
                                  }
                              }
                          ]
                      }
                  },
                  {
                      "roleName": "cloudnative-pg-backup",
                      "roleArn": "arn:aws:iam::role/cloudnative-pg-backup",
                      "attachedPolicies": [
                          "cloudnative-pg-backup"
                      ],
                      "trustPolicy": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "Federated": "*"
                                  },
                                  "Action": [
                                      "sts:AssumeRoleWithWebIdentity"
                                  ],
                                  "Condition": {
                                      "StringEquals": {
                                          "oidc:iss": "https://192.168.0.17:16443"
                                      }
                                  }
                              }
                          ]
                      }
                  },
                  {
                      "roleName": "tempo",
                      "roleArn": "arn:aws:iam::role/tempo",
                      "attachedPolicies": [
                          "tempo"
                      ],
                      "trustPolicy": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "Federated": "*"
                                  },
                                  "Action": [
                                      "sts:AssumeRoleWithWebIdentity"
                                  ],
                                  "Condition": {
                                      "StringEquals": {
                                          "oidc:iss": "https://192.168.0.17:16443"
                                      }
                                  }
                              }
                          ]
                      }
                  }
              ]
          }
        seaweedfs_s3_config.json: |
          {
              "identities": [
                  {
                      "name": "terraform",
                      "actions": [
                          "Admin"
                      ],
                      "credentials": [
                          {
                              "accessKey": "terraform",
                              "secretKey": "{{ .terraform_secretkey }}"
                          }
                      ]
                  },
                  {
                      "name": "misskey",
                      "actions": [
                          "Read:misskey",
                          "Write:misskey",
                          "List:misskey",
                          "Tagging:misskey"
                      ],
                      "credentials": [
                          {
                              "accessKey": "misskey",
                              "secretKey": "{{ .misskey_secretkey }}"
                          }
                      ]
                  },
                  {
                      "name": "oekaki_dengon_game",
                      "actions": [
                          "Read:oekaki-dengon-game",
                          "Write:oekaki-dengon-game",
                          "List:oekaki-dengon-game",
                          "Tagging:oekaki-dengon-game"
                      ],
                      "credentials": [
                          {
                              "accessKey": "oekaki_dengon_game",
                              "secretKey": "{{ .oekaki_dengon_game_secretkey }}"
                          }
                      ]
                  },
                  {
                      "name": "stalwart",
                      "actions": [
                          "Read:stalwart",
                          "Write:stalwart",
                          "List:stalwart",
                          "Tagging:stalwart"
                      ],
                      "credentials": [
                          {
                              "accessKey": "stalwart",
                              "secretKey": "{{ .stalwart_secretkey }}"
                          }
                      ]
                  }
              ]
          }
      engineVersion: v2
      type: Opaque
