apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seaweedfs-default-local
  namespace: seaweedfs
spec:
  hostnames:
    - seaweedfs.local.walnuts.dev
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - kind: Service
          name: seaweedfs-default-filer
          port: 8333
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
