apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seaweedfs-default-minio
  namespace: seaweedfs
spec:
  hostnames:
    - minio.walnuts.dev
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  rules:
    - filters:
        - requestRedirect:
            hostname: seaweedfs.walnuts.dev
            scheme: https
            statusCode: 301
          type: RequestRedirect
      matches:
        - path:
            type: PathPrefix
            value: /
