apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb
spec:
  data:
    - remoteRef:
        key: influxdb
        property: admin-password
      secretKey: admin-password
    - remoteRef:
        key: influxdb
        property: admin-token
      secretKey: admin-token
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: influxdb
    template:
      engineVersion: v2
      type: Opaque
