apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: longhorn-backup-validate-resourceset
  namespace: longhorn-backup-validate
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: longhorn-backup-validate
  resources:
    - kind: Secret
      name: longhorn-backup-validate-manifest-credentials
  strategy: Reconcile
