apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: longhorn-backup-validate
  namespace: longhorn-backup-validate
spec:
  controlPlaneServiceTemplate:
    spec:
      type: LoadBalancer
