apiVersion: gateway.pomerium.io/v1alpha1
kind: PolicyFilter
metadata:
  name: warrior
  namespace: warrior
spec:
  ppl: |
    allow:
      and:
        - claim/my:zitadel:grants:
            has: 356681781363081691:warrior-user
