apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  data:
    - remoteRef:
        key: grafana
        property: admin-password
      secretKey: admin-password
    - remoteRef:
        key: grafana
        property: admin-username
      secretKey: admin-username
    - remoteRef:
        key: grafana
        property: client_secret
      secretKey: client_secret
    - remoteRef:
        key: postgres_passwords
        property: grafana
      secretKey: postgres_password
    - remoteRef:
        key: resend
        property: api-key
      secretKey: smtp_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana
    template:
      engineVersion: v2
      type: Opaque
