apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki
spec:
  data:
    - remoteRef:
        key: redis
        property: password
      secretKey: redispassword
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: loki
    template:
      engineVersion: v2
      type: Opaque
