apiVersion: gateway.pomerium.io/v1alpha1
kind: PolicyFilter
metadata:
  name: hubble-oauth2-proxy
  namespace: cilium-system
spec:
  ppl: |
    allow:
      and:
        - claim/my:zitadel:grants:
            has: 356681781363081691:hubble-user
