core:
  cluster-api: {}
bootstrap:
  kubeadm: {}
  k3s: {}
controlPlane:
  kubeadm: {}
  k3s: {}
infrastructure:
  kubekey:
    version: v4.0.3
    fetchConfig:
      url: https://github.com/walnuts1018/kubekey/releases/download/v4.0.3/infrastructure-components.yaml
resources:
  manager: {}
