apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-biscuit-backup-rclone-07d032
  namespace: minio-biscuit
spec:
  data:
    - remoteRef:
        key: b2
        property: application_key
      secretKey: B2_APPLICATION_KEY
    - remoteRef:
        key: rclone
        property: b2_crypt_password
      secretKey: B2_ENCRYPTED_PASSWORD
    - remoteRef:
        key: rclone
        property: b2_crypt_salt
      secretKey: B2_ENCRYPTED_SALT
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: minio-biscuit-backup-rclone-07d032
    template:
      engineVersion: v2
      type: Opaque
