apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-origin-cert
  namespace: cilium-system
spec:
  data:
    - remoteRef:
        key: cloudflare-origin-cert
        property: tls.crt
      secretKey: tls.crt
    - remoteRef:
        key: cloudflare-origin-cert
        property: tls.key
      secretKey: tls.key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-origin-cert
    template:
      engineVersion: v2
      type: kubernetes.io/tls
