apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cilium-cluster-mesh-01ad8f
  namespace: cilium-system
spec:
  data:
    - remoteRef:
        key: cilium-cluster-mesh
        property: ca.crt
      secretKey: ca.crt
    - remoteRef:
        key: cilium-cluster-mesh
        property: tls.crt
      secretKey: tls.crt
    - remoteRef:
        key: cilium-cluster-mesh
        property: tls.key
      secretKey: tls.key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cilium-cluster-mesh-01ad8f
    template:
      engineVersion: v2
      type: kubernetes.io/tls
