allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: longhorn-local
parameters:
    dataLocality: best-effort
    fromBackup: ""
    numberOfReplicas: "1"
    reclaimPolicy: Retain
    staleReplicaTimeout: "30"
provisioner: driver.longhorn.io

---
