apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: 'cilium'
  source:
    repoURL: 'https://github.com/walnuts1018/infra'
    targetRevision: main
    path: k8s/apps/cilium
    directory:
      recurse: true
      exclude: '{config/*,_*/*}'
      jsonnet:
        tlas:
        - name: 'clusterID'
          value: "1"
          code: true
        - name: 'clusterName'
          value: "biscuit"
        - name: 'k8sServiceHost'
          value: "192.168.0.15"
        - name: 'k8sServicePort'
          value: "6443"
          code: true
        - name: 'ingressLoadBalancerIP'
          value: "192.168.0.159"
        - name: 'clusterMeshLoadBalancerIP'
          value: "192.168.0.160"
        - name: 'enableServiceMonitor'
          value: 'false'
          code: true
        - name: "operatorReplicas"
          value: "1"
          code: true
        - name: 'usek3s'
          value: 'true'
          code: true
        - name: 'clusterMeshPeers'
          value: '[{name: "kurumi",ip:"192.168.0.139"}]'
          code: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
