apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel
  namespace: argocd

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: 'cloudflare-tunnel'
  source:
    repoURL: 'https://github.com/walnuts1018/infra'
    targetRevision: main
    path: k8s/apps/cloudflare-tunnel
    directory:
      recurse: true
      exclude: '{config/*,_*/*}'
      jsonnet:
        tlas:
        - name: 'nameOverride'
          value: 'cloudflare-tunnel-biscuit'
        - name: 'replicas'
          value: "2"
          code: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ServerSideApply=true
    - FailOnSharedResource=true
