apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-readme-stats-ae1c3d
spec:
  data:
    - remoteRef:
        key: github_token
        property: github-readme-stats
      secretKey: github-token
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-readme-stats-ae1c3d
    template:
      engineVersion: v2
      type: Opaque
