[leveldb2]
enabled = false

[cassandra2]
enabled = true
keyspace = "seaweedfs"
hosts = ["scylla-cluster-client.databases.svc"]
username = "seaweedfs"
password = "{{ .scylladb_password }}"
ssl_ca_path = "/etc/seaweedfs/scylladb-ca/ca.crt"
ssl_cert_path = "/etc/seaweedfs/scylladb-client/tls.crt"
ssl_key_path = "/etc/seaweedfs/scylladb-client/tls.key"
localDC = "iwakura"
