apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opentelemetry-collectors-acaba9
spec:
  data:
    - remoteRef:
        key: mackerel
        property: api-key
      secretKey: mackerel-api-key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: opentelemetry-collectors-acaba9
    template:
      engineVersion: v2
      type: Opaque
