apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: walnuk-51af8a
  namespace: walnuk
spec:
  data:
    - remoteRef:
        key: scylladb
        property: walnuk
      secretKey: scylladb_password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: walnuk-51af8a
    template:
      data:
        scylladb_password: '{{ .scylladb_password }}'
        scylladb_username: walnuk
      engineVersion: v2
      type: Opaque
