apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: walnuk
  namespace: walnuk
spec:
  hostnames:
    - waln.uk
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - kind: Service
          name: walnuk-backend
          port: 8080
          weight: 1
      matches:
        - path:
            type: RegularExpression
            value: /[A-Za-z0-9]+
    - filters:
        - extensionRef:
            group: gateway.envoyproxy.io
            kind: HTTPRouteFilter
            name: admin-auth-filter
          type: ExtensionRef
      matches:
        - path:
            type: PathPrefix
            value: /pages/admin
    - backendRefs:
        - kind: Service
          name: walnuk-frontend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
        - path:
            type: PathPrefix
            value: /pages
