apiVersion: v1
kind: Service
metadata:
  labels:
    app: walnuk-backend
    app.kubernetes.io/name: walnuk-backend
  name: walnuk-backend
  namespace: walnuk
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: walnuk-backend
    app.kubernetes.io/name: walnuk-backend
  type: ClusterIP
