apiVersion: v1
kind: Service
metadata:
  labels:
    app: walnuk-frontend
    app.kubernetes.io/name: walnuk-frontend
  name: walnuk-frontend
  namespace: walnuk
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: walnuk-frontend
    app.kubernetes.io/name: walnuk-frontend
  type: ClusterIP
