apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pomerium-global-807db1
spec:
  data:
    - remoteRef:
        key: pomerium
        property: client_id
      secretKey: client_id
    - remoteRef:
        key: pomerium
        property: client_secret
      secretKey: client_secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pomerium-global-807db1
    template:
      engineVersion: v2
      type: Opaque
