apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backupstore-credential-6cfe2a
spec:
  data:
    - remoteRef:
        key: longhorn
        property: minio_secret_key
      secretKey: AWS_SECRET_ACCESS_KEY
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: longhorn-backupstore-credential-6cfe2a
    template:
      data:
        AWS_ACCESS_KEY_ID: abaQ84KgJMyEtxZzW3RW
        AWS_ENDPOINTS: https://minio-biscuit.local.walnuts.dev/
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
      engineVersion: v2
      type: Opaque
