datacenter: iwakura
racks:
- name: iwakura-a
  scyllaConfig: scylla-config
  scyllaAgentConfig: scylla-agent-config
  members: 3
  storage:
    storageClassName: local-path
    capacity: 8Gi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi
  placement:
    nodeAffinity: {}
    tolerations: []
serviceMonitor:
  create: true
