apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-backup-validate
  namespace: longhorn-backup-validate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: longhorn-backup-validate
subjects:
  - kind: ServiceAccount
    name: longhorn-backup-validate
    namespace: longhorn-backup-validate
