apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openchokin-5b8e1f
spec:
  data:
    - remoteRef:
        key: openchokin
        property: ZITADEL_CLIENT_ID
      secretKey: zitade-client-id
    - remoteRef:
        key: openchokin
        property: ZITADEL_CLIENT_SECRET
      secretKey: zitadel-client-secret
    - remoteRef:
        key: openchokin
        property: NEXTAUTH_SECRET
      secretKey: nextauth-secret
    - remoteRef:
        key: postgres_passwords
        property: postgres
      secretKey: postgres-admin-password
    - remoteRef:
        key: postgres_passwords
        property: openchokin
      secretKey: postgres-user-password
    - remoteRef:
        key: redis
        property: password
      secretKey: redis-password
    - remoteRef:
        key: openchokin
        property: CACHE_PASSWORD
      secretKey: cache-password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openchokin-5b8e1f
    template:
      engineVersion: v2
      type: Opaque
