apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - git:
      repoURL: https://github.com/walnuts1018/infra
      revision: main
      files:
      - path: "k8s/apps/*/app.json5"
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      source:
        repoURL: 'https://github.com/walnuts1018/infra'
        targetRevision: main
        path: '{{.path.path}}'
        directory:
          recurse: true
          exclude: '{config/*,_*/*}'
          jsonnet:
            tlas:
            - name: ''
              value: ''
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - ServerSideApply=true
        - FailOnSharedResource=true
  templatePatch: |
    metadata:
      annotations:
        {{.name}}: '{{.name}}'
