apiVersion: gateway.pomerium.io/v1alpha1
kind: PolicyFilter
metadata:
  name: longhorn-oauth2-proxy
  namespace: longhorn-system
spec:
  ppl: |
    allow:
      and:
        - claim/my:zitadel:grants:
            has: 356681781363081691:longhorn-admin
