apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-operator
  namespace: kubevirt
spec:
  template:
    spec:
      containers:
      - name: virt-operator
        resources:
          requests:
            cpu: 10m
            memory: 280Mi
          limits:
            cpu: "1"
            memory: 1Gi
