apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubevirt/kubevirt/releases/download/v1.7.1/kubevirt-operator.yaml
- https://github.com/kubevirt/kubevirt/releases/download/v1.7.1/kubevirt-cr.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.64.0/cdi-operator.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.64.0/cdi-cr.yaml
patches:
- path: kubevirt-patch.yaml
  target:
    kind: KubeVirt
    name: kubevirt
- target:
    kind: Deployment
    name: kubevirt-operator
    namespace: kubevirt
  patch: |-
    - op: "replace"
      path: "/spec/template/spec/containers/0/resources"
      value: {"requests": {"cpu": "10m", "memory": "280Mi"}, "limits": {"cpu": "1", "memory": "1Gi"}}
- target:
    kind: Deployment
    name: cdi-operator
    namespace: cdi
  patch: |-
    - op: "replace"
      path: "/spec/template/spec/containers/0/resources"
      value: {"requests": {"cpu": "8m", "memory": "183Mi"}, "limits": {"cpu": "1", "memory": "1Gi"}}
