apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-biscuit-backup-trigger
  namespace: minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio-biscuit-backup-trigger
subjects:
  - kind: ServiceAccount
    name: minio-biscuit-backup-trigger
    namespace: minio-biscuit
