apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stalwart
    app.kubernetes.io/name: stalwart
  name: stalwart
  namespace: stalwart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stalwart
      app.kubernetes.io/name: stalwart
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stalwart
        app.kubernetes.io/name: stalwart
    spec:
      containers:
        - image: docker.io/stalwartlabs/stalwart:v0.15.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          name: stalwart
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 443
              name: https
            - containerPort: 25
              name: smtp
            - containerPort: 465
              name: smtps
            - containerPort: 993
              name: imaps
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext: null
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz/live
              port: 8080
            periodSeconds: 10
          volumeMounts:
            - mountPath: /opt/stalwart/etc/config.toml
              name: stalwart-config
              readOnly: true
              subPath: config.toml
            - mountPath: /tmp
              name: tmp
      serviceAccountName: stalwart
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: stalwart
              app.kubernetes.io/name: stalwart
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      volumes:
        - name: stalwart-config
          secret:
            items:
              - key: config.toml
                path: config.toml
            secretName: stalwart-443f90
        - emptyDir: {}
          name: tmp
