apiVersion: v1
kind: Service
metadata:
  labels:
    app: stalwart
    app.kubernetes.io/name: stalwart
  name: stalwart
  namespace: stalwart
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
    - name: smtp
      port: 25
      protocol: TCP
      targetPort: smtp
    - name: smtps
      port: 465
      protocol: TCP
      targetPort: smtps
    - name: imaps
      port: 993
      protocol: TCP
      targetPort: imaps
  selector:
    app: stalwart
    app.kubernetes.io/name: stalwart
  type: ClusterIP
