apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fitbit-manager-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: fitbit_manager
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: fitbit-manager-db-password
    template:
      data:
        password: '{{ .password }}'
        username: fitbit_manager
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: grafana
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-db-password
    template:
      data:
        password: '{{ .password }}'
        username: grafana
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hedgedoc-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: hedgedoc
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hedgedoc-db-password
    template:
      data:
        password: '{{ .password }}'
        username: hedgedoc
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: nextcloud
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-db-password
    template:
      data:
        password: '{{ .password }}'
        username: nextcloud
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oekaki-dengon-game-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: oekaki_dengon_game
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oekaki-dengon-game-db-password
    template:
      data:
        password: '{{ .password }}'
        username: oekaki_dengon_game
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openchokin-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: openchokin
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openchokin-db-password
    template:
      data:
        password: '{{ .password }}'
        username: openchokin
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wakatime-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: wakatime
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wakatime-db-password
    template:
      data:
        password: '{{ .password }}'
        username: wakatime
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: zitadel
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zitadel-db-password
    template:
      data:
        password: '{{ .password }}'
        username: zitadel
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ac-hacking-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: ac_hacking
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ac-hacking-db-password
    template:
      data:
        password: '{{ .password }}'
        username: ac_hacking
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mucaron-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: mucaron
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mucaron-db-password
    template:
      data:
        password: '{{ .password }}'
        username: mucaron
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: affine
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: affine-db-password
    template:
      data:
        password: '{{ .password }}'
        username: affine
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: n8n
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-db-password
    template:
      data:
        password: '{{ .password }}'
        username: n8n
      engineVersion: v2
      type: kubernetes.io/basic-auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-db-password
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: stalwart
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: stalwart-db-password
    template:
      data:
        password: '{{ .password }}'
        username: stalwart
      engineVersion: v2
      type: kubernetes.io/basic-auth
