apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser-password-e616d3
spec:
  data:
    - remoteRef:
        key: postgres_passwords
        property: postgres
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postgres-superuser-password-e616d3
    template:
      data:
        password: '{{ .password }}'
        username: postgres
      engineVersion: v2
      type: kubernetes.io/basic-auth
