apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: postgresql-default
  name: postgresql-default-rw-expose
  namespace: databases
spec:
  loadBalancerIP: 192.168.0.141
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgresql-default
    cnpg.io/instanceRole: primary
  type: LoadBalancer
