apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-oauth2-proxy
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/longhorn-oauth2-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
