apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: oekaki-dengon-game
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/apps/oekaki-dengon-game
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
