apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mpeg-dash-encoder-65bb67
spec:
  data:
    - remoteRef:
        key: mpeg-dash-encoder
        property: admin_token
      secretKey: admin_token
    - remoteRef:
        key: mpeg-dash-encoder
        property: jwt_sign_secret
      secretKey: jwt_sign_secret
    - remoteRef:
        key: mpeg-dash-encoder
        property: minio_secret_key
      secretKey: minio_secret_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mpeg-dash-encoder-65bb67
    template:
      engineVersion: v2
      type: Opaque
