apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: repo
spec:
  url: https://charts.zitadel.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: release
spec:
  chart:
    spec:
      chart: zitadel
      version: 7.8.0
  values:
    zitadel:
      configmapConfig:
        ExternalDomain: auth.walnuts.dev
        TLS:
          Enabled: false
        ExternalPort: 443
        ExternalSecure: true
      masterkeySecretName: "zitadel-secret"
      configSecretName: zitadel-secret
      configSecretKey: config-yaml
    replicaCount: 1
    image:
      tag: "v2.44.1"
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: auth.walnuts.dev
          paths:
            - path: /
              pathType: Prefix
    env:
    #  - name: ZITADEL_LOG_LEVEL
    #    value: "debug"
    nodeSelector:
      kubernetes.io/hostname: cake
    metrics:
      enabled: true
