apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ipu-948900
spec:
  data:
    - remoteRef:
        key: ipu-oauth2-proxy
        property: client-id
      secretKey: client-id
    - remoteRef:
        key: ipu-oauth2-proxy
        property: client-secret
      secretKey: client-secret
    - remoteRef:
        key: ipu-oauth2-proxy
        property: cookie-secret
      secretKey: session-secret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ipu-948900
    template:
      engineVersion: v2
      type: Opaque
