apiVersion: v1
kind: Service
metadata:
    labels:
        app: samba
        app.kubernetes.io/name: samba
    name: samba
    namespace: samba
spec:
    loadBalancerIP: 192.168.0.132
    ports:
        - port: 445
          protocol: TCP
          targetPort: 10445
    selector:
        app: samba
        app.kubernetes.io/name: samba
    type: LoadBalancer

---
