apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-proxy
  namespace: argocd
spec:
  hostnames:
    - argocd.local.walnuts.dev
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: argocd-proxy
      matches:
        - path:
            type: PathPrefix
            value: /
