machine:
  network:
    interfaces:
    - interface: end0
      dhcp: false
      addresses:
      - 192.168.0.14/24
      routes:
      - network: 0.0.0.0/0
        gateway: 192.168.0.1
    nameservers:
    - 192.168.0.1
  time:
    servers:
    - ntp.jst.mfeed.ad.jp
  install:
    disk: /dev/sda
    wipe: true
cluster:
  allowSchedulingOnControlPlanes: true
  network:
    cni:
      name: none
  proxy:
    disabled: true
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: cheese
auto: off
