apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network-exporter
resources:
- role.yaml
- deployment.yaml
- rolebinding.yaml
- externalsecret.yaml
- sa.yaml
- image-policy.yaml
components:
- ../../components/deployment-with-vpa
