apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: walnuts-dev-www
  namespace: walnuts-dev
spec:
  hostnames:
    - www.walnuts.dev
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  rules:
    - filters:
        - requestRedirect:
            hostname: walnuts.dev
            scheme: https
            statusCode: 301
          type: RequestRedirect
