apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba-secret-dbea5d
spec:
  data:
    - remoteRef:
        key: samba
        property: password
      secretKey: account-samba
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: samba-secret-dbea5d
    template:
      engineVersion: v2
      type: Opaque
