apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mega
  namespace: samba
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 176Gi
  storageClassName: longhorn-single-encrypted
