apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: misskey-usercontent
  namespace: misskey
spec:
  hostnames:
    - misskeyusercontent.walnuts.dev
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - kind: Service
          name: seaweedfs-default-filer
          namespace: seaweedfs
          port: 8333
          weight: 1
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /misskey/files
              type: ReplacePrefixMatch
        - requestHeaderModifier:
            add:
              - name: X-Forwarded-Prefix
                value: /files
          type: RequestHeaderModifier
      matches:
        - path:
            type: PathPrefix
            value: /files
