apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: misskey-db-password-0bfec8
spec:
  data:
    - remoteRef:
        key: misskey
        property: dbpassword
      secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: misskey-db-password-0bfec8
    template:
      data:
        password: '{{ .password }}'
        username: misskey
      engineVersion: v2
      type: kubernetes.io/basic-auth
