apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-pvc
spec:
  storageClassName: longhorn
  volumeName: misskey
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
