apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: misskey
  namespace: seaweedfs
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: misskey
  to:
    - group: ""
      kind: Service
