core:
  cluster-api: {}
bootstrap:
  talos: {}
controlPlane:
  talos: {}
infrastructure:
  kubevirt: {}
addon:
  helm: {}
resources:
  manager:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
