apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fitbit-manager-3ddd96
spec:
  data:
    - remoteRef:
        key: fitbit_manager
        property: client_id
      secretKey: client_id
    - remoteRef:
        key: fitbit_manager
        property: client_secret
      secretKey: client_secret
    - remoteRef:
        key: fitbit_manager
        property: cookie_secret
      secretKey: cookie_secret
    - remoteRef:
        key: postgres_passwords
        property: fitbit_manager
      secretKey: postgres_password
    - remoteRef:
        key: influxdb
        property: fitbit-manager-auth-token
      secretKey: influxdb_auth_token
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: fitbit-manager-3ddd96
    template:
      engineVersion: v2
      type: Opaque
