apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komga-9a709c
spec:
  data:
    - remoteRef:
        key: komga
        property: client-secret
      secretKey: clientsecret
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: komga-9a709c
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            items:
              - key: application.yml
                templateAs: Values
            name: komga-secret-template-f1b676
          target: Data
      type: Opaque
