apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-operator
  namespace: cloudflare-tunnel-operator
spec:
  data:
    - remoteRef:
        key: cloudflare
        property: cloudflare-tunnel-operator
      secretKey: cloudflareAPIToken
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tunnel-operator
    template:
      engineVersion: v2
      type: Opaque
