apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator-helm
  namespace: argocd
spec:
  destination:
    namespace: redis-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: redis-operator
    helm:
      releaseName: redis-operator
      values: |
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 15m
            memory: 32Mi

        # redisOperator:
        #   extraArgs:
        #   - "-zap-log-level=debug"

        tolerations:
        - key: "node.walnuts.dev/low-performance"
          operator: "Exists"
    repoURL: https://ot-container-kit.github.io/helm-charts/
    targetRevision: 0.23.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
