apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pomerium
resources:
- https://github.com/pomerium/ingress-controller/config/gateway-api\?ref=v0.32.0
patches:
- target:
    kind: Namespace
    name: pomerium
  patch: |-
    - op: "delete"
- target:
    kind: Deployment
    name: pomerium
    namespace: pomerium
  patch: |-
    - op: "replace"
      path: "/spec/template/spec/containers/0/resources"
      value: {"requests": {"cpu": "10m", "memory": "32Mi"}, "limits": {"cpu": "1", "memory": "1Gi"}}
