replicas: 1
# Scylla Operator log level, 0-9 (higher number means more detailed logs)
logLevel: 2
resources:
  requests:
    cpu: 2m
    memory: 70Mi
tolerations: []

webhookServerReplicas: 1
webhookServerResources:
  requests:
    cpu: 2m
    memory: 12Mi
webhookServerTolerations: []
