replicas: 1
# Scylla Operator log level, 0-9 (higher number means more detailed logs)
logLevel: 2
resources:
  requests:
    cpu: 100m
    memory: 20Mi
tolerations: []

webhookServerReplicas: 1
webhookServerResources:
  requests:
    cpu: 10m
    memory: 20Mi
webhookServerTolerations: []
