# TODO: Delete This
name: Trigger TFC via Commit

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  commit-trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - run: git switch -c tfc-trigger
      - name: Update dummy file
        run: |
          date > terraform/dummy

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add terraform/dummy
          git commit -m "dummy: trigger TFC run"
          git push origin tfc-trigger --force

      - uses: actions/create-github-app-token@v2
        id: generate_token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Set env
        run: |
          echo "GH_TOKEN=${{ steps.generate_token.outputs.token }}" >> $GITHUB_ENV

      - name: create PR
        run: |
          gh pr create --title "dummy: trigger TFC run" --body "dummy: trigger TFC run" --base main --head tfc-trigger
          gh pr merge --merge --auto
